[package]
name = "qrc-opensource-rs"
version = "0.1.0"
authors = ["Quantum Resistant Cryptography (QRC)"]
description = "The free opensource version of the QRC library"
documentation = "https://docs.rs/qrc-opensource-rs"
edition = "2021"
license = "GNU Affero General Public License v3.0"
repository = "https://github.com/Quantum-Resistant-Cryptography/qrc-opensource-rs"
keywords = ["cryptography", "quantum", "post-quantum", "rust"]
categories = ["cryptography", "security"]

[dependencies]
